[package]
name = "tcp_test"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/Dodgemaster1/tcp-test"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
criterion = "0.8.2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
